services:
  process.response.pipeline.default:
    class: League\Pipeline\Pipeline
    arguments:
      - ~
      - '@process.response.stage.format_response.default'
      - '@process.response.stage.create_response.json'
