services:
  process.response.stage.format_response.default:
    class: Dnovikov32\HttpProcess\Response\Stage\FormatResponse
    arguments:
      - '@process.response.formatter.default_formatter'

  process.response.stage.create_response.default:
    class: Dnovikov32\HttpProcess\Response\Stage\CreateResponse
    arguments:
      - '@process.response.transformer.default_transformer'

  process.response.stage.create_response.json:
    class: Dnovikov32\HttpProcess\Response\Stage\CreateResponse
    arguments:
      - '@process.response.transformer.json_transformer'
