services:
  http_process.response.transformer.default_transformer:
    class: Dnovikov32\HttpProcessBundle\Response\Transformer\DefaultTransformer

  http_process.response.transformer.json_transformer:
    class: Dnovikov32\HttpProcessBundle\Response\Transformer\JsonTransformer
    arguments:
      - '@http_process.serializer'
