services:
  process.response.transformer.default_transformer:
    class: Dnovikov32\HttpProcess\Response\Transformer\DefaultTransformer

  process.response.transformer.json_transformer:
    class: Dnovikov32\HttpProcess\Response\Transformer\JsonTransformer
    arguments:
      - '@process.serializer'
